import type { Place } from "@/domain/models";
export interface PlacesProvider {
  list(): Promise<Place[]>;
  get(id: string): Promise<Place | null>;
}
type Seed = [
  string,
  string,
  string,
  number,
  number,
  string,
  Place["environment"],
  Place["intents"],
  number,
  number,
  number | null,
  string,
  number,
  boolean,
  string,
  string,
];
const seeds: Seed[] = [
  [
    "virginia-water",
    "Virginia Water",
    "Windsor Great Park",
    51.409,
    -0.59,
    "Lakeside walk",
    "outdoor",
    ["walk", "scenic", "relax", "date"],
    60,
    150,
    0,
    "Free entry · parking extra",
    0.6,
    true,
    "https://www.windsorgreatpark.co.uk/explore/the-park/virginia-water/",
    "A lake, a waterfall, and a good reason to put your phone away.",
  ],
  [
    "swinley-forest",
    "Swinley Forest",
    "Bracknell, Berkshire",
    51.383,
    -0.739,
    "Woodland",
    "outdoor",
    ["walk", "active", "scenic"],
    45,
    120,
    0,
    "Free entry · parking extra",
    0.55,
    true,
    "https://www.windsorgreatpark.co.uk/explore/the-forest/swinley-forest/",
    "Take the forest paths. You don’t need to make a whole day of it.",
  ],
  [
    "watts-gallery",
    "Watts Gallery",
    "Compton, Surrey",
    51.221404,
    -0.628863,
    "Art & culture",
    "mixed",
    ["culture", "unusual", "date", "relax"],
    60,
    120,
    null,
    "Check admission",
    0.85,
    false,
    "https://www.wattsgallery.org.uk/",
    "Victorian art and a very different sort of afternoon.",
  ],
  [
    "lightwater",
    "Lightwater Country Park",
    "Lightwater, Surrey",
    51.347,
    -0.679,
    "Country park",
    "outdoor",
    ["walk", "scenic", "kids", "relax"],
    45,
    90,
    0,
    "Free entry",
    0.5,
    true,
    "https://www.surreyheath.gov.uk/parks-and-countryside/lightwater-country-park",
    "Heathland paths, without planning a serious expedition.",
  ],
  [
    "frimley-lodge",
    "Frimley Lodge Park",
    "Frimley Green, Surrey",
    51.3,
    -0.726,
    "Park & canal",
    "outdoor",
    ["walk", "kids", "relax"],
    40,
    90,
    0,
    "Free entry",
    0.35,
    true,
    "https://www.surreyheath.gov.uk/parks-and-countryside/frimley-lodge-park",
    "Swap the sofa for the Basingstoke Canal towpath.",
  ],
  [
    "look-out",
    "The Look Out",
    "Bracknell, Berkshire",
    51.386,
    -0.74,
    "Science discovery",
    "indoor",
    ["kids", "unusual", "culture"],
    90,
    150,
    null,
    "Check tickets",
    0.7,
    false,
    "https://www.bracknell-forest.gov.uk/leisure-and-events/look-out-discovery-centre",
    "Hands-on science for curious kids. A rainy-day decision made.",
  ],
  [
    "wellington",
    "Wellington Country Park",
    "Riseley, Berkshire",
    51.3592235,
    -0.9612239,
    "Family day out",
    "outdoor",
    ["kids", "active"],
    120,
    240,
    null,
    "Check tickets",
    0.6,
    true,
    "https://wellingtoncountrypark.co.uk/",
    "Give the kids room to roam, and make an afternoon of it.",
  ],
  [
    "dinton",
    "Dinton Pastures",
    "Hurst, Berkshire",
    51.442,
    -0.876,
    "Lakes & country park",
    "outdoor",
    ["scenic", "walk", "kids", "active"],
    60,
    150,
    0,
    "Free entry · parking extra",
    0.6,
    true,
    "https://www.wokinghamcountryside.co.uk/dinton-pastures-country-park",
    "Lakeside paths and a change of pace just outside Wokingham.",
  ],
  [
    "savill",
    "The Savill Garden",
    "Windsor Great Park",
    51.415,
    -0.599,
    "Gardens",
    "outdoor",
    ["scenic", "date", "relax"],
    60,
    120,
    null,
    "Seasonal admission",
    0.75,
    true,
    "https://www.windsorgreatpark.co.uk/explore/the-gardens/the-savill-garden/",
    "Let somebody else do the gardening. You just do the wandering.",
  ],
  [
    "windsor-long-walk",
    "The Long Walk",
    "Windsor, Berkshire",
    51.477,
    -0.607,
    "Royal landscape",
    "outdoor",
    ["walk", "scenic", "date"],
    45,
    120,
    0,
    "Free entry",
    0.55,
    true,
    "https://www.windsorgreatpark.co.uk/explore/the-park/the-long-walk-and-deer-park/",
    "One remarkably straight path. One very good view of Windsor.",
  ],
  [
    "milestones",
    "Milestones Museum",
    "Basingstoke, Hampshire",
    51.266,
    -1.108,
    "Living history",
    "indoor",
    ["culture", "kids", "unusual"],
    90,
    180,
    null,
    "Check tickets",
    0.8,
    false,
    "https://www.milestonesmuseum.org.uk/",
    "Walk through Hampshire’s past without getting caught in the rain.",
  ],
  [
    "rural-life",
    "Rural Life Living Museum",
    "Tilford, Surrey",
    51.184,
    -0.771,
    "Living history",
    "mixed",
    ["culture", "kids", "unusual"],
    90,
    180,
    null,
    "Check tickets",
    0.9,
    false,
    "https://rural-life.org.uk/",
    "Old workshops, rural stories, and something genuinely different.",
  ],
  [
    "farnham-castle",
    "Farnham Castle",
    "Farnham, Surrey",
    51.2185201,
    -0.8023933,
    "Historic keep",
    "mixed",
    ["culture", "scenic", "unusual"],
    45,
    90,
    null,
    "Check access & admission",
    0.7,
    true,
    "https://www.farnhamcastle.com/",
    "A short climb into a much older Farnham. Check visitor access first.",
  ],
  [
    "newlands-corner",
    "Newlands Corner",
    "Guildford, Surrey",
    51.232,
    -0.507,
    "Downs & viewpoint",
    "outdoor",
    ["scenic", "walk", "date"],
    45,
    120,
    0,
    "Free entry · parking extra",
    0.65,
    true,
    "https://www.surreycc.gov.uk/culture-and-leisure/countryside/sites/visitor-information/newlands-corner",
    "Get above the everyday, with a view across the Surrey Hills.",
  ],
  [
    "alice-holt",
    "Alice Holt Forest",
    "Farnham, Hampshire",
    51.173,
    -0.85,
    "Forest trails",
    "outdoor",
    ["walk", "kids", "active"],
    60,
    180,
    0,
    "Free entry · parking extra",
    0.5,
    true,
    "https://www.forestryengland.uk/alice-holt-forest",
    "A proper forest escape, with as much walking as you feel like.",
  ],
  [
    "fleet-pond",
    "Fleet Pond",
    "Fleet, Hampshire",
    51.2887683,
    -0.8248165,
    "Nature reserve",
    "outdoor",
    ["walk", "scenic", "relax"],
    45,
    90,
    0,
    "Free entry",
    0.6,
    true,
    "https://www.hart.gov.uk/countryside-and-leisure/fleet-pond",
    "A quiet waterside detour. Go gently; this is a nature reserve.",
  ],
  [
    "yateley-common",
    "Yateley Common",
    "Yateley, Hampshire",
    51.3281927,
    -0.8206037,
    "Heathland",
    "outdoor",
    ["walk", "relax", "scenic"],
    45,
    120,
    0,
    "Free entry",
    0.7,
    true,
    "https://www.hants.gov.uk/thingstodo/countryside/finder/yateleycommon",
    "A nearby stretch of heathland that makes a small escape feel bigger.",
  ],
  [
    "california",
    "California Country Park",
    "Finchampstead, Berkshire",
    51.3800656,
    -0.87157,
    "Country park",
    "outdoor",
    ["kids", "walk", "relax"],
    45,
    120,
    0,
    "Free entry · parking extra",
    0.45,
    true,
    "https://www.wokingham.gov.uk/parks-and-countryside/california-country-park",
    "Take the lake loop and leave the rest of the afternoon open.",
  ],
  [
    "south-hill",
    "South Hill Park",
    "Bracknell, Berkshire",
    51.393,
    -0.753,
    "Arts centre & grounds",
    "mixed",
    ["culture", "date", "food", "scenic"],
    45,
    120,
    null,
    "Grounds & ticketed events",
    0.7,
    false,
    "https://www.southhillpark.org.uk/",
    "Art, grounds, and the possibility of making an evening of it.",
  ],
  [
    "reading-museum",
    "Reading Museum",
    "Reading, Berkshire",
    51.457,
    -0.97,
    "Museum",
    "indoor",
    ["culture", "kids", "unusual"],
    60,
    120,
    0,
    "Free entry",
    0.65,
    false,
    "https://www.readingmuseum.org.uk/",
    "A small history detour in the middle of town.",
  ],
  [
    "merl",
    "The Museum of English Rural Life",
    "Reading, Berkshire",
    51.449,
    -0.961,
    "Museum",
    "indoor",
    ["culture", "unusual", "kids"],
    60,
    120,
    0,
    "Free entry",
    0.9,
    false,
    "https://merl.reading.ac.uk/",
    "Surprisingly absorbing stories about the countryside and the people in it.",
  ],
  [
    "brooklands",
    "Brooklands Museum",
    "Weybridge, Surrey",
    51.3549958,
    -0.4646239,
    "Motoring & aviation",
    "mixed",
    ["culture", "kids", "unusual"],
    120,
    240,
    null,
    "Check tickets",
    0.85,
    false,
    "https://www.brooklandsmuseum.com/",
    "Old racing machines and aircraft. A day out with a different gear.",
  ],
  [
    "farnborough-air",
    "Farnborough Air Sciences Trust",
    "Farnborough, Hampshire",
    51.2822851,
    -0.7534956,
    "Aviation museum",
    "indoor",
    ["culture", "unusual", "kids"],
    45,
    90,
    0,
    "Free entry · check opening days",
    0.85,
    false,
    "https://www.airsciences.org.uk/",
    "Aviation history close to home. Opening days need checking.",
  ],
  [
    "guildford-castle",
    "Guildford Castle Grounds",
    "Guildford, Surrey",
    51.233,
    -0.573,
    "Gardens & history",
    "outdoor",
    ["scenic", "culture", "date", "relax"],
    30,
    60,
    0,
    "Grounds free · keep extra",
    0.45,
    true,
    "https://www.guildford.gov.uk/castle",
    "A little history and garden time in the heart of Guildford.",
  ],
  [
    "norden-farm",
    "Norden Farm",
    "Maidenhead, Berkshire",
    51.5157802,
    -0.7463915,
    "Arts & cinema",
    "indoor",
    ["culture", "date", "unusual"],
    90,
    150,
    null,
    "Check programme & tickets",
    0.75,
    false,
    "https://norden.farm/",
    "Let the programme choose your evening. Book a performance you fancy.",
  ],
  [
    "red-kangaroo",
    "Oxygen Reading",
    "Reading, Berkshire",
    51.4602939,
    -1.0067089,
    "Trampoline activity",
    "indoor",
    ["active", "kids"],
    60,
    90,
    null,
    "Book & check tickets",
    0.6,
    false,
    "https://oxygenactiveplay.co.uk/activity-parks/reading/",
    "Trade sitting still for something considerably more energetic.",
  ],
  [
    "craggy",
    "Blue Spider Climbing",
    "Guildford, Surrey",
    51.2601023,
    -0.5682091,
    "Indoor climbing",
    "indoor",
    ["active", "unusual", "date"],
    60,
    120,
    null,
    "Check booking & induction",
    0.85,
    false,
    "https://spiderclimbing.com/blue-spider/",
    "A climbing session beats another evening on the sofa. Check induction requirements.",
  ],
  [
    "everyman",
    "Everyman Wokingham",
    "Wokingham, Berkshire",
    51.41,
    -0.835,
    "Cinema",
    "indoor",
    ["date", "relax", "culture"],
    120,
    180,
    null,
    "Check film times & tickets",
    0.4,
    false,
    "https://www.everymancinema.com/venues-list/x11nv-everyman-wokingham/",
    "Pick a film, put your phone away, and settle in.",
  ],
  [
    "escape-reading",
    "Escape Reading",
    "Queens Walk, Reading",
    51.4545707,
    -0.9772849,
    "Escape rooms",
    "indoor",
    ["unusual", "active", "date"],
    60,
    90,
    null,
    "Book & check tickets",
    0.95,
    false,
    "https://www.escapereading.co.uk/",
    "You have an hour. Work together, solve it, and get out.",
  ],
  [
    "painshill",
    "Painshill",
    "Cobham, Surrey",
    51.3311252,
    -0.4247878,
    "Landscape garden",
    "outdoor",
    ["scenic", "walk", "date", "unusual"],
    90,
    180,
    null,
    "Check tickets",
    0.9,
    true,
    "https://www.painshill.co.uk/",
    "A landscape made for wandering, with a few unexpected turns.",
  ],
];
export const PLACES: Place[] = seeds.map(
  ([
    id,
    name,
    area,
    lat,
    lng,
    category,
    environment,
    intents,
    min,
    max,
    cost,
    costLabel,
    novelty,
    daylightOnly,
    website,
    tagline,
  ]) => ({
    id,
    name,
    area,
    coordinates: { lat, lng },
    aliases:
      id === "everyman"
        ? ["Everyman"]
        : id === "guildford-castle"
          ? ["Guildford Castle"]
          : [],
    category,
    environment,
    intents,
    company: intents.includes("kids")
      ? ["family", "friends"]
      : intents.includes("date")
        ? ["solo", "couple", "friends"]
        : ["solo", "couple", "friends"],
    duration: [min, max],
    cost,
    costLabel,
    novelty,
    daylightOnly,
    exposed: id === "newlands-corner",
    website,
    source: website,
    tagline,
    description: tagline,
    notes: [
      "Opening times, admission and access can change. Check the official website before leaving.",
      cost === 0
        ? "Free entry does not include parking, food or optional activities."
        : "Admission has not been verified. Confirm tickets and availability with the venue.",
      "Visit durations and journey times are SideQuest estimates, not venue guarantees.",
    ],
  }),
);
export const curatedPlaces: PlacesProvider = {
  async list() {
    return PLACES;
  },
  async get(id) {
    return PLACES.find((p) => p.id === id) || null;
  },
};
export const IMAGE_FILES: Record<
  string,
  { file: string; credit: string; license: string }
> = {
  "virginia-water": {
    file: "Virginia Water Lake 1.jpg",
    credit: "Wikimedia Commons contributors",
    license: "See source licence",
  },
  "swinley-forest": {
    file: "Swinley Forest - geograph.org.uk - 1876520.jpg",
    credit: "Alan Hunt / Geograph",
    license: "CC BY-SA 2.0",
  },
  "watts-gallery": {
    file: "Watts Gallery (Restored).JPG",
    credit: "Wikimedia Commons contributors",
    license: "See source licence",
  },
};
const photos: Record<string, NonNullable<Place["image"]>> = {
  "yateley-common": {
    url: "/images/yateley.webp",
    credit: "Andrew Smith / Geograph",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File:Yateley_Common_-_geograph.org.uk_-_170514.jpg",
  },
  "farnborough-air": {
    url: "/images/fast.webp",
    credit: "Lewis Hulbert",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/wiki/File:FAST_Cody_Pavilion.JPG",
  },
  savill: {
    url: "/images/savill.webp",
    credit: "Daderot",
    license: "CC0 1.0",
    source:
      "https://commons.wikimedia.org/wiki/File:Savill_Garden_-_Windsor_Great_Park,_England_-_DSC06400.jpg",
  },
  dinton: {
    url: "/images/dinton.webp",
    credit: "Des Blenkinsopp / Geograph",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File:Dinton_Pastures_Country_Park_-_geograph.org.uk_-_3840977.jpg",
  },
  "fleet-pond": {
    url: "/images/fleet.webp",
    credit: "Michelle Salter",
    license: "CC BY-SA 3.0",
    source: "https://commons.wikimedia.org/wiki/File:Fleet_Pond.jpg",
  },
  "windsor-long-walk": {
    url: "/images/windsor.webp",
    credit: "Randolph Croft",
    license: "CC BY 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File:The_Long_Walk,_Windsor_Castle_(2942942928).jpg",
  },
  milestones: {
    url: "/images/milestones.webp",
    credit: "Colin Smith / Geograph",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File:Milestones_Museum_-_geograph.org.uk_-_3035188.jpg",
  },
  "virginia-water": {
    url: "/images/lake.webp",
    credit: "Suzanne Knights",
    license: "Public domain",
    source: "https://commons.wikimedia.org/wiki/File:Virginia_Water_Lake_1.jpg",
  },
  "swinley-forest": {
    url: "/images/forest.webp",
    credit: "Alan Hunt / Geograph",
    license: "CC BY-SA 2.0",
    source:
      "https://commons.wikimedia.org/wiki/File:Swinley_Forest_-_geograph.org.uk_-_1876520.jpg",
  },
  "watts-gallery": {
    url: "/images/gallery.webp",
    credit: "© Watts Gallery / Fsalino",
    license: "CC BY-SA 3.0",
    source:
      "https://commons.wikimedia.org/wiki/File:Watts_Gallery_(Restored).JPG",
  },
};
PLACES.forEach((p) => {
  p.image = photos[p.id];
});

// Official regular weekend hours checked 7 October 2026. Bank holidays require checking.
const fastMuseum = PLACES.find((p) => p.id === "farnborough-air");
if (fastMuseum) {
  fastMuseum.hours = [{ days: [6, 0], open: 600, close: 960 }];
  fastMuseum.notes.unshift(
    "Regular opening: Saturdays and Sundays, 10am–4pm. Check bank-holiday access on the official site. Source checked 7 October 2026.",
  );
}
